// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for our ROS 2 module
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1/ros2-basics',
        'module-1/python-agents-rclpy',
        'module-1/urdf-humanoids',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twins & Physical AI',
      items: [
        'module-2/index',
        'module-2/digital-twins-physical-ai',
        'module-2/gazebo-physics-simulation',
        'module-2/unity-high-fidelity-interaction',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      items: [
        'module-3/index',
        'module-3/nvidia-isaac-sim',
        'module-3/isaac-ros-vslam',
        'module-3/nav2-humanoid-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Autonomous Humanoids',
      items: [
        'module-4/index',
        'module-4/llm-planning',
        'module-4/voice-to-action',
        'module-4/autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
