openapi: 3.0.0
info:
  title: RAG Agent Frontend Integration API
  description: API contracts for frontend integration with RAG agent backend
  version: 1.0.0
  contact:
    name: AI Physical Book Team

servers:
  - url: http://localhost:8000
    description: Local RAG Agent Backend
  - url: https://api.rag-agent.example.com
    description: Production RAG Agent Backend

paths:
  /query:
    post:
      summary: Submit a query to the RAG agent
      description: Sends a user query to the RAG agent and returns a contextual response
      operationId: submitQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response from the RAG agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          description: Bad request - invalid query format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - RAG Agent

  /health:
    get:
      summary: Health check for the RAG agent service
      description: Checks if the RAG agent service is running and accessible
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Service is unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Health

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The user's question or query
          example: "What are the key concepts of machine learning?"
          minLength: 1
          maxLength: 1000
        top_k:
          type: integer
          description: Number of results to retrieve
          default: 5
          minimum: 1
          maximum: 20
          example: 5
        include_metadata:
          type: boolean
          description: Whether to include metadata in results
          default: true
          example: true

    AgentResponse:
      type: object
      required:
        - query
        - answer
        - retrieved_contexts
        - sources
      properties:
        query:
          type: string
          description: The original query that was submitted
          example: "What are the key concepts of machine learning?"
        answer:
          type: string
          description: The RAG agent's response to the query
          example: "Machine learning involves algorithms that learn patterns from data..."
        retrieved_contexts:
          type: array
          description: List of contexts used to generate the response
          items:
            $ref: '#/components/schemas/RetrievedContext'
          example:
            - id: "context_123"
              content: "Machine learning is a subset of AI that enables systems to learn..."
              score: 0.92
              metadata:
                source_api: "https://external-api.example.com"
                fetch_timestamp: 1678886400
        sources:
          type: array
          description: List of sources referenced in the response
          items:
            type: string
          example:
            - "https://external-api.example.com"
            - "https://book-content.example.com"

    RetrievedContext:
      type: object
      required:
        - id
        - content
        - score
        - metadata
      properties:
        id:
          type: string
          description: Unique identifier for this context
          example: "context_123"
        content:
          type: string
          description: The content text used for context
          example: "Machine learning is a subset of AI that enables systems to learn..."
        score:
          type: number
          description: Relevance score (0.0 to 1.0)
          format: float
          minimum: 0.0
          maximum: 1.0
          example: 0.92
        metadata:
          type: object
          description: Additional metadata about the context source
          additionalProperties: true
          example:
            source_api: "https://external-api.example.com"
            fetch_timestamp: 1678886400
            content_length: 1250

    HealthResponse:
      type: object
      required:
        - status
        - service
      properties:
        status:
          type: string
          description: Health status of the service
          enum: [healthy, degraded, unavailable]
          example: "healthy"
        service:
          type: string
          description: Name of the service
          example: "RAG Agent API"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid query format"
        details:
          type: object
          description: Additional error details (optional)
          example:
            field: "query"
            reason: "Query is too short"

  parameters:
    TopKParam:
      name: top_k
      in: query
      description: Number of results to retrieve
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 20
        default: 5
      example: 5

tags:
  - name: RAG Agent
    description: Endpoints for interacting with the RAG agent
  - name: Health
    description: Service health and status endpoints